//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.Language {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Import {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Import() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockManagement.Language.Import.Import", typeof(Import).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose file.
        /// </summary>
        public static string chooseFile {
            get {
                return ResourceManager.GetString("chooseFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Commit.
        /// </summary>
        public static string commit {
            get {
                return ResourceManager.GetString("commit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Skipped as duplicate.
        /// </summary>
        public static string duplicatesSkipped {
            get {
                return ResourceManager.GetString("duplicatesSkipped", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Excel Import.
        /// </summary>
        public static string excelImport {
            get {
                return ResourceManager.GetString("excelImport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed the conversion process for a given excel column to the specified parameter. This happened for the parameter {0} and the column number {1}..
        /// </summary>
        public static string failedConversion {
            get {
                return ResourceManager.GetString("failedConversion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string import {
            get {
                return ResourceManager.GetString("import", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Imported.
        /// </summary>
        public static string imported {
            get {
                return ResourceManager.GetString("imported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string preview {
            get {
                return ResourceManager.GetString("preview", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select Excel-sheet:.
        /// </summary>
        public static string selectExcelSheet {
            get {
                return ResourceManager.GetString("selectExcelSheet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Selected File is currently being used by another process and cannot be opened..
        /// </summary>
        public static string selectedFileInUse {
            get {
                return ResourceManager.GetString("selectedFileInUse", resourceCulture);
            }
        }
    }
}
