<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\StockManagement.Sales.Core\StockManagement.Sales.Core.csproj" />
    <ProjectReference Include="..\StockManagement.Customers.Core\StockManagement.Customers.Core.csproj" />
    <ProjectReference Include="..\StockManagement.Settings.Core\StockManagement.Settings.Core.csproj" />
    <ProjectReference Include="..\StockManagement.Kernel\StockManagement.Kernel.csproj" />
    <ProjectReference Include="..\StockManagement.Infrastructure\StockManagement.Infrastructure.csproj" />
    <ProjectReference Include="..\StockManagement.Import.Core\StockManagement.Import.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FastEndpoints" Version="8.3.0" />
  </ItemGroup>

</Project>
