//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.Language {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Users {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Users() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockManagement.Language.Users.Users", typeof(Users).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string fullName {
            get {
                return ResourceManager.GetString("fullName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string position {
            get {
                return ResourceManager.GetString("position", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string role {
            get {
                return ResourceManager.GetString("role", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rights.
        /// </summary>
        public static string rights {
            get {
                return ResourceManager.GetString("rights", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string standard {
            get {
                return ResourceManager.GetString("standard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        public static string createUser {
            get {
                return ResourceManager.GetString("createUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save User.
        /// </summary>
        public static string saveUser {
            get {
                return ResourceManager.GetString("saveUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete User.
        /// </summary>
        public static string deleteUser {
            get {
                return ResourceManager.GetString("deleteUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete user {0}?.
        /// </summary>
        public static string deleteUserPrompt {
            get {
                return ResourceManager.GetString("deleteUserPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A user with this username already exists:.
        /// </summary>
        public static string usernameAlreadyExists {
            get {
                return ResourceManager.GetString("usernameAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You cannot delete your own account...
        /// </summary>
        public static string cannotDeleteSelf {
            get {
                return ResourceManager.GetString("cannotDeleteSelf", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View clients.
        /// </summary>
        public static string permCustomersRead {
            get {
                return ResourceManager.GetString("permCustomersRead", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit clients.
        /// </summary>
        public static string permCustomersWrite {
            get {
                return ResourceManager.GetString("permCustomersWrite", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View stock items.
        /// </summary>
        public static string permStockItemsRead {
            get {
                return ResourceManager.GetString("permStockItemsRead", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit stock items.
        /// </summary>
        public static string permStockItemsWrite {
            get {
                return ResourceManager.GetString("permStockItemsWrite", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View invoices.
        /// </summary>
        public static string permSalesRead {
            get {
                return ResourceManager.GetString("permSalesRead", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create sales.
        /// </summary>
        public static string permSalesWrite {
            get {
                return ResourceManager.GetString("permSalesWrite", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View settings.
        /// </summary>
        public static string permSettingsRead {
            get {
                return ResourceManager.GetString("permSettingsRead", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit settings.
        /// </summary>
        public static string permSettingsWrite {
            get {
                return ResourceManager.GetString("permSettingsWrite", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manage users.
        /// </summary>
        public static string permUsersManage {
            get {
                return ResourceManager.GetString("permUsersManage", resourceCulture);
            }
        }
    }
}
