//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.Language {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Suppliers {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Suppliers() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockManagement.Language.Suppliers.Suppliers", typeof(Suppliers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string supplier {
            get {
                return ResourceManager.GetString("supplier", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        public static string suppliers {
            get {
                return ResourceManager.GetString("suppliers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string contactName {
            get {
                return ResourceManager.GetString("contactName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string currency {
            get {
                return ResourceManager.GetString("currency", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lead time (days).
        /// </summary>
        public static string leadTimeDays {
            get {
                return ResourceManager.GetString("leadTimeDays", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create Supplier.
        /// </summary>
        public static string createSupplier {
            get {
                return ResourceManager.GetString("createSupplier", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete Supplier.
        /// </summary>
        public static string deleteSupplier {
            get {
                return ResourceManager.GetString("deleteSupplier", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A supplier with this name already exists:.
        /// </summary>
        public static string supplierAlreadyExists {
            get {
                return ResourceManager.GetString("supplierAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Supplier is assigned to stock items and can't be deleted..
        /// </summary>
        public static string supplierInUse {
            get {
                return ResourceManager.GetString("supplierInUse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete {0}?.
        /// </summary>
        public static string supplierDeletionPrompt {
            get {
                return ResourceManager.GetString("supplierDeletionPrompt", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Lead time cannot be negative...
        /// </summary>
        public static string leadTimeNegative {
            get {
                return ResourceManager.GetString("leadTimeNegative", resourceCulture);
            }
        }
    }
}
