//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.Language {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StockItems {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StockItems() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockManagement.Language.StockItems.StockItems", typeof(StockItems).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Check In.
        /// </summary>
        public static string checkIn {
            get {
                return ResourceManager.GetString("checkIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        public static string checkOut {
            get {
                return ResourceManager.GetString("checkOut", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Check In/Out.
        /// </summary>
        public static string checkStock {
            get {
                return ResourceManager.GetString("checkStock", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Checkin.
        /// </summary>
        public static string checkin {
            get {
                return ResourceManager.GetString("checkin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string checkout {
            get {
                return ResourceManager.GetString("checkout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create Stock item.
        /// </summary>
        public static string createItem {
            get {
                return ResourceManager.GetString("createItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete Item.
        /// </summary>
        public static string deleteItem {
            get {
                return ResourceManager.GetString("deleteItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete selected Items.
        /// </summary>
        public static string deleteSelectedItems {
            get {
                return ResourceManager.GetString("deleteSelectedItems", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Descritpion.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Factor.
        /// </summary>
        public static string factor {
            get {
                return ResourceManager.GetString("factor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hide unavailable items.
        /// </summary>
        public static string hideUnavailableItems {
            get {
                return ResourceManager.GetString("hideUnavailableItems", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A stock item with this code already exists:.
        /// </summary>
        public static string itemAlreadyExists {
            get {
                return ResourceManager.GetString("itemAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete {0}?.
        /// </summary>
        public static string itemDeletionPrompt {
            get {
                return ResourceManager.GetString("itemDeletionPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not enough stock:.
        /// </summary>
        public static string itemsUnavailable {
            get {
                return ResourceManager.GetString("itemsUnavailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Machine.
        /// </summary>
        public static string machine {
            get {
                return ResourceManager.GetString("machine", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string manufacturer {
            get {
                return ResourceManager.GetString("manufacturer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Map columns to properties.
        /// </summary>
        public static string mapProperties {
            get {
                return ResourceManager.GetString("mapProperties", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rim diameter.
        /// </summary>
        public static string rimDiameter {
            get {
                return ResourceManager.GetString("rimDiameter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search codes:.
        /// </summary>
        public static string searchCodes {
            get {
                return ResourceManager.GetString("searchCodes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search location:.
        /// </summary>
        public static string searchLocation {
            get {
                return ResourceManager.GetString("searchLocation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select item type:.
        /// </summary>
        public static string selectItemType {
            get {
                return ResourceManager.GetString("selectItemType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select manufacturer:.
        /// </summary>
        public static string selectManufacturer {
            get {
                return ResourceManager.GetString("selectManufacturer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select stock item type:.
        /// </summary>
        public static string selectType {
            get {
                return ResourceManager.GetString("selectType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} items will be deleted. Are you sure?.
        /// </summary>
        public static string selectedItemsDeletionPrompt {
            get {
                return ResourceManager.GetString("selectedItemsDeletionPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show picture.
        /// </summary>
        public static string showPicture {
            get {
                return ResourceManager.GetString("showPicture", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Spare part.
        /// </summary>
        public static string sparePart {
            get {
                return ResourceManager.GetString("sparePart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stock item.
        /// </summary>
        public static string stockItem {
            get {
                return ResourceManager.GetString("stockItem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stock items.
        /// </summary>
        public static string stockItems {
            get {
                return ResourceManager.GetString("stockItems", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Removed items due to them not being available in stock (Amount = 0)..
        /// </summary>
        public static string stockItemsRemoved {
            get {
                return ResourceManager.GetString("stockItemsRemoved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tire.
        /// </summary>
        public static string tire {
            get {
                return ResourceManager.GetString("tire", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tire dimensions.
        /// </summary>
        public static string tireDimensions {
            get {
                return ResourceManager.GetString("tireDimensions", resourceCulture);
            }
        }
    }
}
