//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.Language {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockManagement.Language.Common.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Additional Information.
        /// </summary>
        public static string additionalInformation {
            get {
                return ResourceManager.GetString("additionalInformation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Change item info.
        /// </summary>
        public static string changeInfo {
            get {
                return ResourceManager.GetString("changeInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string information {
            get {
                return ResourceManager.GetString("information", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please check your input..
        /// </summary>
        public static string invalidInput {
            get {
                return ResourceManager.GetString("invalidInput", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string miscellaneous {
            get {
                return ResourceManager.GetString("miscellaneous", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string more {
            get {
                return ResourceManager.GetString("more", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string previous {
            get {
                return ResourceManager.GetString("previous", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string quit {
            get {
                return ResourceManager.GetString("quit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string reason {
            get {
                return ResourceManager.GetString("reason", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string row {
            get {
                return ResourceManager.GetString("row", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string searchBoxDefault {
            get {
                return ResourceManager.GetString("searchBoxDefault", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string show {
            get {
                return ResourceManager.GetString("show", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string undo {
            get {
                return ResourceManager.GetString("undo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured. Please contact the support to resolve the issue..
        /// </summary>
        public static string unexpectedError {
            get {
                return ResourceManager.GetString("unexpectedError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string width {
            get {
                return ResourceManager.GetString("width", resourceCulture);
            }
        }
    }
}
