//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.Language {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Settings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Settings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockManagement.Language.Settings.Settings", typeof(Settings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adjust size of border for inner window.
        /// </summary>
        public static string adjustDialogBorderSize {
            get {
                return ResourceManager.GetString("adjustDialogBorderSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        public static string german {
            get {
                return ResourceManager.GetString("german", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to For language changes to take effect, please restart the application..
        /// </summary>
        public static string languageChangedMessage {
            get {
                return ResourceManager.GetString("languageChangedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select language:.
        /// </summary>
        public static string selectLanguage {
            get {
                return ResourceManager.GetString("selectLanguage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string spanish {
            get {
                return ResourceManager.GetString("spanish", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Company settings.
        /// </summary>
        public static string companySettings {
            get {
                return ResourceManager.GetString("companySettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        public static string companyName {
            get {
                return ResourceManager.GetString("companyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tax ID.
        /// </summary>
        public static string taxId {
            get {
                return ResourceManager.GetString("taxId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string currency {
            get {
                return ResourceManager.GetString("currency", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VAT rate (%).
        /// </summary>
        public static string vatRate {
            get {
                return ResourceManager.GetString("vatRate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Payment term (days).
        /// </summary>
        public static string paymentTermInDays {
            get {
                return ResourceManager.GetString("paymentTermInDays", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to First invoice number.
        /// </summary>
        public static string firstInvoiceNumber {
            get {
                return ResourceManager.GetString("firstInvoiceNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to First customer id.
        /// </summary>
        public static string firstCustomerId {
            get {
                return ResourceManager.GetString("firstCustomerId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Currency decimal digits.
        /// </summary>
        public static string currencyDecimalDigits {
            get {
                return ResourceManager.GetString("currencyDecimalDigits", resourceCulture);
            }
        }
    }
}
