//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Numbers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Numbers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockManagement.Language.Numbers.Numbers", typeof(Numbers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        public static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MILMILLIONES.
        /// </summary>
        public static string billion {
            get {
                return ResourceManager.GetString("billion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCHO.
        /// </summary>
        public static string eight {
            get {
                return ResourceManager.GetString("eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIECIOCHO.
        /// </summary>
        public static string eighteen {
            get {
                return ResourceManager.GetString("eighteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCHOCIENTOS.
        /// </summary>
        public static string eighthundred {
            get {
                return ResourceManager.GetString("eighthundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCHENTA.
        /// </summary>
        public static string eighty {
            get {
                return ResourceManager.GetString("eighty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONCE.
        /// </summary>
        public static string eleven {
            get {
                return ResourceManager.GetString("eleven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUINCE.
        /// </summary>
        public static string fifteen {
            get {
                return ResourceManager.GetString("fifteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CINCUENTA.
        /// </summary>
        public static string fifty {
            get {
                return ResourceManager.GetString("fifty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CINCO.
        /// </summary>
        public static string five {
            get {
                return ResourceManager.GetString("five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUINIENTOS.
        /// </summary>
        public static string fivehundred {
            get {
                return ResourceManager.GetString("fivehundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUATRO.
        /// </summary>
        public static string four {
            get {
                return ResourceManager.GetString("four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUATROCIENTOS.
        /// </summary>
        public static string fourhundred {
            get {
                return ResourceManager.GetString("fourhundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATORCE.
        /// </summary>
        public static string fourteen {
            get {
                return ResourceManager.GetString("fourteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUARENTA.
        /// </summary>
        public static string fourty {
            get {
                return ResourceManager.GetString("fourty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIEN.
        /// </summary>
        public static string hundred {
            get {
                return ResourceManager.GetString("hundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIENTO.
        /// </summary>
        public static string hundredSomething {
            get {
                return ResourceManager.GetString("hundredSomething", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MILLÓN.
        /// </summary>
        public static string million {
            get {
                return ResourceManager.GetString("million", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MILLONES.
        /// </summary>
        public static string multipleMillions {
            get {
                return ResourceManager.GetString("multipleMillions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BILLONES.
        /// </summary>
        public static string multipleTrillions {
            get {
                return ResourceManager.GetString("multipleTrillions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUEVE.
        /// </summary>
        public static string nine {
            get {
                return ResourceManager.GetString("nine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOVECIENTOS.
        /// </summary>
        public static string ninehundred {
            get {
                return ResourceManager.GetString("ninehundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIECINUEVE.
        /// </summary>
        public static string nineteen {
            get {
                return ResourceManager.GetString("nineteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOVENTA.
        /// </summary>
        public static string ninety {
            get {
                return ResourceManager.GetString("ninety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNO.
        /// </summary>
        public static string one {
            get {
                return ResourceManager.GetString("one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIETE.
        /// </summary>
        public static string seven {
            get {
                return ResourceManager.GetString("seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETECIENTOS.
        /// </summary>
        public static string sevenhundred {
            get {
                return ResourceManager.GetString("sevenhundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIECISIETE.
        /// </summary>
        public static string seventeen {
            get {
                return ResourceManager.GetString("seventeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETENTA.
        /// </summary>
        public static string seventy {
            get {
                return ResourceManager.GetString("seventy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEIS.
        /// </summary>
        public static string six {
            get {
                return ResourceManager.GetString("six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEISCIENTOS.
        /// </summary>
        public static string sixhundred {
            get {
                return ResourceManager.GetString("sixhundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIECISÉIS.
        /// </summary>
        public static string sixteen {
            get {
                return ResourceManager.GetString("sixteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SESENTA.
        /// </summary>
        public static string sixty {
            get {
                return ResourceManager.GetString("sixty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIEZ.
        /// </summary>
        public static string ten {
            get {
                return ResourceManager.GetString("ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRECE.
        /// </summary>
        public static string thirteen {
            get {
                return ResourceManager.GetString("thirteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TREINTA.
        /// </summary>
        public static string thirty {
            get {
                return ResourceManager.GetString("thirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIL.
        /// </summary>
        public static string thousand {
            get {
                return ResourceManager.GetString("thousand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRES.
        /// </summary>
        public static string three {
            get {
                return ResourceManager.GetString("three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRESCIENTOS.
        /// </summary>
        public static string threehundred {
            get {
                return ResourceManager.GetString("threehundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BILLÓN.
        /// </summary>
        public static string trillion {
            get {
                return ResourceManager.GetString("trillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOCE.
        /// </summary>
        public static string twelve {
            get {
                return ResourceManager.GetString("twelve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VEINTE.
        /// </summary>
        public static string twenty {
            get {
                return ResourceManager.GetString("twenty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VEINTIOCHO.
        /// </summary>
        public static string twentyeight {
            get {
                return ResourceManager.GetString("twentyeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VEINTICINCO.
        /// </summary>
        public static string twentyfive {
            get {
                return ResourceManager.GetString("twentyfive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VEINTICUATRO.
        /// </summary>
        public static string twentyfour {
            get {
                return ResourceManager.GetString("twentyfour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VEINTINUEVE.
        /// </summary>
        public static string twentynine {
            get {
                return ResourceManager.GetString("twentynine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VEINTIUNO.
        /// </summary>
        public static string twentyone {
            get {
                return ResourceManager.GetString("twentyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VEINTISIETE.
        /// </summary>
        public static string twentyseven {
            get {
                return ResourceManager.GetString("twentyseven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VEINTISÉIS.
        /// </summary>
        public static string twentysix {
            get {
                return ResourceManager.GetString("twentysix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VEINTITRÉS.
        /// </summary>
        public static string twentythree {
            get {
                return ResourceManager.GetString("twentythree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VEINTIDÓS.
        /// </summary>
        public static string twentytwo {
            get {
                return ResourceManager.GetString("twentytwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOS.
        /// </summary>
        public static string two {
            get {
                return ResourceManager.GetString("two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOSCIENTOS.
        /// </summary>
        public static string twohundred {
            get {
                return ResourceManager.GetString("twohundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CERO.
        /// </summary>
        public static string zero {
            get {
                return ResourceManager.GetString("zero", resourceCulture);
            }
        }
    }
}
