//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.Language {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Invoices {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Invoices() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockManagement.Language.Invoices.Invoices", typeof(Invoices).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add to Shopping Cart.
        /// </summary>
        public static string addToShoppingCart {
            get {
                return ResourceManager.GetString("addToShoppingCart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bar.
        /// </summary>
        public static string cash {
            get {
                return ResourceManager.GetString("cash", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel invoice.
        /// </summary>
        public static string cancelInvoice {
            get {
                return ResourceManager.GetString("cancelInvoice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string cancelled {
            get {
                return ResourceManager.GetString("cancelled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancellation reason.
        /// </summary>
        public static string cancelReason {
            get {
                return ResourceManager.GetString("cancelReason", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Erstellungsdatum.
        /// </summary>
        public static string creationDate {
            get {
                return ResourceManager.GetString("creationDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kredit.
        /// </summary>
        public static string credit {
            get {
                return ResourceManager.GetString("credit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Die Anzahl der verkauften Artikel ist zu hoch. (Unzureichende Artikel auf Lager).
        /// </summary>
        public static string exceptionShoppingCartItemOutOfRange {
            get {
                return ResourceManager.GetString("exceptionShoppingCartItemOutOfRange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ablaufsdatum.
        /// </summary>
        public static string expirationDate {
            get {
                return ResourceManager.GetString("expirationDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CDC.
        /// </summary>
        public static string cdc {
            get {
                return ResourceManager.GetString("cdc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SIFEN status.
        /// </summary>
        public static string transmissionStatus {
            get {
                return ResourceManager.GetString("transmissionStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Credit Note.
        /// </summary>
        public static string creditNote {
            get {
                return ResourceManager.GetString("creditNote", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Credit Note ID.
        /// </summary>
        public static string creditNoteId {
            get {
                return ResourceManager.GetString("creditNoteId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not enough in stock, only available:.
        /// </summary>
        public static string insufficientStock {
            get {
                return ResourceManager.GetString("insufficientStock", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The payment amount must be greater than zero..
        /// </summary>
        public static string invalidPaymentAmount {
            get {
                return ResourceManager.GetString("invalidPaymentAmount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rechnung.
        /// </summary>
        public static string invoice {
            get {
                return ResourceManager.GetString("invoice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invoice ID.
        /// </summary>
        public static string invoiceId {
            get {
                return ResourceManager.GetString("invoiceId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invoice not found..
        /// </summary>
        public static string invoiceNotFound {
            get {
                return ResourceManager.GetString("invoiceNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invoices.
        /// </summary>
        public static string invoices {
            get {
                return ResourceManager.GetString("invoices", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New sale.
        /// </summary>
        public static string newSale {
            get {
                return ResourceManager.GetString("newSale", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The payment amount exceeds the invoice's amount due..
        /// </summary>
        public static string paymentExceedsAmountDue {
            get {
                return ResourceManager.GetString("paymentExceedsAmountDue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Verkaufsbedingung.
        /// </summary>
        public static string saleCondition {
            get {
                return ResourceManager.GetString("saleCondition", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search in dates:.
        /// </summary>
        public static string searchDates {
            get {
                return ResourceManager.GetString("searchDates", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search Invoice IDs:.
        /// </summary>
        public static string searchInvoiceIds {
            get {
                return ResourceManager.GetString("searchInvoiceIds", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        public static string sell {
            get {
                return ResourceManager.GetString("sell", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shopping Cart.
        /// </summary>
        public static string shoppingCart {
            get {
                return ResourceManager.GetString("shoppingCart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shopping Cart Items.
        /// </summary>
        public static string shoppingCartItems {
            get {
                return ResourceManager.GetString("shoppingCartItems", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Steuer.
        /// </summary>
        public static string tax {
            get {
                return ResourceManager.GetString("tax", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Sale condition is invalid...
        /// </summary>
        public static string saleConditionInvalid {
            get {
                return ResourceManager.GetString("saleConditionInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to At least one item is required...
        /// </summary>
        public static string saleItemsRequired {
            get {
                return ResourceManager.GetString("saleItemsRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Payment method is invalid...
        /// </summary>
        public static string paymentMethodInvalid {
            get {
                return ResourceManager.GetString("paymentMethodInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string statusPending {
            get {
                return ResourceManager.GetString("statusPending", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string statusPaid {
            get {
                return ResourceManager.GetString("statusPaid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Overdue.
        /// </summary>
        public static string statusOverdue {
            get {
                return ResourceManager.GetString("statusOverdue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invoice {0} saved..
        /// </summary>
        public static string invoiceSavedToast {
            get {
                return ResourceManager.GetString("invoiceSavedToast", resourceCulture);
            }
        }
    }
}
