//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.Language {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Customers {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Customers() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockManagement.Language.Customers.Customers", typeof(Customers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string clients {
            get {
                return ResourceManager.GetString("clients", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create Customer.
        /// </summary>
        public static string createCustomer {
            get {
                return ResourceManager.GetString("createCustomer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string customer {
            get {
                return ResourceManager.GetString("customer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Customer ID.
        /// </summary>
        public static string customerId {
            get {
                return ResourceManager.GetString("customerId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string customerName {
            get {
                return ResourceManager.GetString("customerName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Customer not found..
        /// </summary>
        public static string customerNotFound {
            get {
                return ResourceManager.GetString("customerNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Identification number (C.I. / RUC).
        /// </summary>
        public static string identificationNumber {
            get {
                return ResourceManager.GetString("identificationNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        public static string lastname {
            get {
                return ResourceManager.GetString("lastname", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string phoneNumber {
            get {
                return ResourceManager.GetString("phoneNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Postbox number.
        /// </summary>
        public static string postboxNumber {
            get {
                return ResourceManager.GetString("postboxNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save Customer.
        /// </summary>
        public static string saveCustomer {
            get {
                return ResourceManager.GetString("saveCustomer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search customer IDs:.
        /// </summary>
        public static string searchCustomerIds {
            get {
                return ResourceManager.GetString("searchCustomerIds", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search in customers:.
        /// </summary>
        public static string searchCustomers {
            get {
                return ResourceManager.GetString("searchCustomers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search lastnames:.
        /// </summary>
        public static string searchLastnames {
            get {
                return ResourceManager.GetString("searchLastnames", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search names:.
        /// </summary>
        public static string searchNames {
            get {
                return ResourceManager.GetString("searchNames", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select Customer:.
        /// </summary>
        public static string selectCustomer {
            get {
                return ResourceManager.GetString("selectCustomer", resourceCulture);
            }
        }
    }
}
