//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.Language {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Reports {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Reports() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockManagement.Language.Reports.Reports", typeof(Reports).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string reports {
            get {
                return ResourceManager.GetString("reports", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stock value.
        /// </summary>
        public static string stockValueReport {
            get {
                return ResourceManager.GetString("stockValueReport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sales by period.
        /// </summary>
        public static string salesByPeriod {
            get {
                return ResourceManager.GetString("salesByPeriod", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sales by customer.
        /// </summary>
        public static string salesByCustomer {
            get {
                return ResourceManager.GetString("salesByCustomer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Low stock.
        /// </summary>
        public static string lowStockReport {
            get {
                return ResourceManager.GetString("lowStockReport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total value.
        /// </summary>
        public static string totalValue {
            get {
                return ResourceManager.GetString("totalValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total units.
        /// </summary>
        public static string totalUnits {
            get {
                return ResourceManager.GetString("totalUnits", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invoices.
        /// </summary>
        public static string invoiceCount {
            get {
                return ResourceManager.GetString("invoiceCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No sales in this period..
        /// </summary>
        public static string noSalesForPeriod {
            get {
                return ResourceManager.GetString("noSalesForPeriod", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No items below their minimum stock..
        /// </summary>
        public static string noLowStockItems {
            get {
                return ResourceManager.GetString("noLowStockItems", resourceCulture);
            }
        }
    }
}
